# -*- coding: utf-8 -*-
"""sentiment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XBsZkQ-FCk4yLOQZqxzg__FpMAWt-3gH
"""

import nltk
from nltk.sentiment import SentimentIntensityAnalyzer
nltk.download('punkt')
nltk.download('vader_lexicon')

def analyze_sentiment(text):
    # Pre-processing
    text = text.lower()

    # Tokenization
    words = nltk.word_tokenize(text)

    # Sentiment Analysis
    sentiment = SentimentIntensityAnalyzer()
    sentiment_score = sentiment.polarity_scores(text)['compound']

    # Aggregation
    if sentiment_score >= 0.05:
        sentiment = "Positive"
    elif sentiment_score <= -0.05:
        sentiment = "Negative"
    else:
        sentiment = "Neutral"

    # Output
    return sentiment

def analyze_sentiments(text_dataset):
    sentiments = []
    for text in text_dataset:
        sentiment = analyze_sentiment(text)
        sentiments.append(sentiment)
    return sentiments

text_dataset = [
    "This is a positive text",
    "This is a negative text",
    "This is a neutral text",
    "I am feeling happy today",
    "I am feeling sad today",
    "I am feeling indifferent today",
    "The movie was great",
    "The movie was terrible",
    "The movie was okay",
    "I love ice cream"
]
sentiments = analyze_sentiments(text_dataset)
for i, sentiment in enumerate(sentiments):
    print("Text", i + 1, "Sentiment:", sentiment)

text = input("Enter the text you want for sentiment anlysis\n")
sentiment = analyze_sentiment(text)
print("Sentiment:", sentiment)